//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kendoui.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        public int pizzaid { get; set; }
        public string pizzaname { get; set; }
        public int rate { get; set; }
    }
}
